KILOBYTE = 1024
MEGABYTE = KILOBYTE * KILOBYTE
MEDIA_TYPE_IMAGE = "image"

MEDIA_TYPE_LIST = [
    MEDIA_TYPE_IMAGE,
]

MEDIA_TYPE_CHOICES = [[s, s] for s in MEDIA_TYPE_LIST]

MEDIA_ACCEPTED_IMAGE = [
    "image/jpeg",
    "image/png",
    "image/gif",
    "image/apng",
    "image/webp",
]

ALL_MEDIA_ACCEPTED = MEDIA_ACCEPTED_IMAGE

MEDIA_METADATA_WIDTH = "width"
MEDIA_METADATA_HEIGHT = "height"
MEDIA_METADATA_EXTENSION = "extension"

MEDIA_METADATA_FIELDS = [
    MEDIA_METADATA_WIDTH,
    MEDIA_METADATA_HEIGHT,
]

MEDIA_MAX_SIZE_IMAGE = 2 * MEGABYTE
