# Generated by Django 4.1.7 on 2023-03-17 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import media.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="",
                        validators=[
                            media.validators.FileMediaValidator(
                                content_types=[
                                    "image/jpeg",
                                    "image/png",
                                    "image/gif",
                                    "image/apng",
                                    "image/webp",
                                ]
                            )
                        ],
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("thumbnail", models.ImageField(upload_to="")),
                ("file_name", models.CharField(blank=True, max_length=600, null=True)),
                ("file_size", models.IntegerField(blank=True, null=True)),
                (
                    "file_type",
                    models.CharField(choices=[["image", "image"]], max_length=32),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "abstract": False,
            },
        ),
    ]
